title: NLU/CompSem
description: The syllabus for the course Natural Language Understanding and Computational Semantics (DS-GA/LING-GA 1012) at New York University
theme: just-the-docs

url: https://nyu-dsga1012-s23.github.io/syllabus

#aux_links:
#  Template Repository: https://github.com/NYU-DSGA1012-S23/syllabus
nav_external_links:
  - title: Brightspace (Gradebook)
    url: https://brightspace.nyu.edu/
    hide_icon: false
  - title: Gradescope (Feedback)
    url: https://www.gradescope.com/
    hide_icon: false
  - title: Campuswire (Discussion)
    url: https://campuswire.com/p/GB6E76357/
    hide_icon: false
  - title: GitHub (Assignments)
    url: https://github.com/nyu-dsga1012-s23
    hide_icon: false


collections:
  modules:

defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [ ]
  blanklines: false
  profile: false