title: NLU/CompSem
description: The syllabus for the course Natural Language Understanding and Computational Semantics (DS-GA/LING-GA 1012) at New York University
theme: just-the-docs

url: https://nyu-dsga1012-s23.github.io/

#aux_links:
#  Template Repository: https://github.com/NYU-DSGA1012-S23/syllabus
collections:
  modules:

defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false